### ISSUE TITLE
Use of MCE in Digital Signature XML Signature parts.

### ISSUE THREAD

**Issue by murata2makoto** [sc34wg4/opcRevision#3]
Subclasue 12.5 has new text.  It is intended to clarify the use of MCE in Digital Signature XML Signature parts.

> 12.5 Digital Signature Markup
> 12.5.1 General
> The content of a Digital Signature XML Signature part shall be anXML document.  The requirements (including MCE processing before validation and subsequent processing) specified in §8.2.5 apply.
>
>  After the removal of any extensions by an MCE processor asspecified in ISO/IEC 29500-3, the content of each Digital Signature XML Signature part shall be a schema-valid XML document against xmldsig-core-schema.xsd, as specified in the W3C Recommendation “XML-Signature Syntax and Processing”, and opc-digSig.xsd (see §C.4).

Is the use of MCE allowed in Digital Signature XML Signature parts? In my understanding, it is allowed.  I thus wrote the above paragraphs.

My understanding is based on 13.6.2 in the currently published OPC.

> 13.6.2 Markup Compatibility Namespace for Package Digital Signatures
> 
> The package implementer shall not use the Markup Compatibility namespace, as specified in Annex F within the package-specific Object element. The package implementer shall consider the use of the Markup Compatibility namespace within the package-specific Object element to be an error. [M6.32]
> 
> Format designers might specify an application-defined package part format that allows for the embedding of versioned or extended content that might not be fully understood by all present and future implementations. Producers might create such embedded versioned or extended content and consumers might encounter such content. [O6.12] [Example: An XML package part format might rely on Markup Compatibility elements and attributes to embed such versioned or extended content. end example]
> 
> If an application allows for a single part to contain information that might not be fully understood by all implementations, then the format designer shall carefully design the signing and verification policies to account for the possibility of different implementations being used for each action in the sequence of content creation, content signing, and signature verification. Producers and consumers shall account for this possibility in their signing and verification processing. [M6.33]

However, I feel a bit nervous.  Do we really allow MCE anywhere in digital XML signature parts?  For example, can the root element be an MCE Choice element?  My paragraphs allow such an MCE Choice element.

One could argue that MCE is allowed only within application-defined Object elements.

But why do we have to mention MCE-processing-before-valiation then? Absolutely anything is allowed within application-defined Object elements.

Finally, I find a cut-and-paste error in 12.5.10.3 (Application-Defined Object Element).
  
> The Markup Compatibility namespace, as specified in Annex E, shall  not be used within the OPC-specific Object element.

This paragraph should be revised or removed.

**Comment by RexJaeschke** [comment]
Here at the Milan, IT, F2F meeting, SC 34/WG4 decided it needed help from MS experts.

We plan to close-out this revision my late March 2020, so will need to resolve this before then.

**Comment by dcleblanc** [comment]
There should not be any MCE within the idPackageObject Object element. That should only be XMLDSig elements present in the XMLDSig specification, namely the Manifest, and the SignatureProperties, which should only contain the self-attested signature time. I don't believe it would parse correctly if it did exist, and it wouldn't be (as far as I know) ignored by the canonicalization. The Object element with Id of idOfficeObject also should only contain SignatureInfoV1 and optionally SignatureInfoV2 elements.

The Object element containing XAdES information should also not have any MCE, and could possibly cause parser failures if it did.

If an application were to add its own Object element, then it can, according to the standard, put anything it likes into there.

I would tend to agree that this:

The requirements (including MCE processing before validation and subsequent processing) specified in §8.2.5 apply.

may be in error, because I don't believe the signature XML ever does any MCE processing. In addition, I am not aware of any MCE processing when obtaining the hashes of the various XML parts within the document - there is certainly no transform for this listed in any of the references.

It has been some time since I was in the code every day, so it is possible my understanding is out of date.

**Comment by murata2makoto** [comment]
It appears that we also need inputs from somebody currently involved in digital signatures for MS Office.

**Comment by murata2makoto** [comment]
The last paragraph of 12.5.10.3 (Application-Defined Object Element) is an editorial mistake.  It should be dropped.

> The Markup Compatibility namespace, as specified in Annex E, shall not be used within the OPC-specific Object element.

@dcleblanc wrote:

>The Object element containing XAdES information should also not have any MCE, and could possibly cause parser failures if it did.

This is true but cannot be addressed by OPC.  It should be addressed by a future extension for XAdES (or MS-OFFCRYPTO)

**Comment by RexJaeschke** [comment]
Discussion from the 2019-04-24 WG4 Teleconference:

We assumed that David's sentence "I don't believe the signature XML ever does any MCE processing" is true, and then discussed Options 1 and 2 (see below).  This assumption should be checked by MS experts.  If it is incorrect, we do not have to consider these options.

Option 1: Change Part 2 to disallow MCE processing in that context, but, in theory, this could break existing implementations.

Option 2: Leave OPC as is, allowing MCE processing, but have Part 1 disallow that for OOXML implementations.

It seems that Part 1 is silent about the use of MCE in Parts other than Part 1.

**Comment by AlfredHellstern** [comment]
I’m checking with my contacts in the Office team.

**Comment by dcleblanc** [comment]
To summarize a conversation with Dan Jump, we do not do MCE processing while parsing the signature XML file. In addition, when creating the hash of the various document XML parts that are being signed, we also do not do MCE processing, so all of the XML is covered by the signature.

MCE does allow a situation where a document could appear differently to different versions of a consumer, but since it is all signed, you can investigate that and see what caused that, which would reveal malicious use of MCE.

**Comment by murata2makoto** [comment]
Thanks, David, Dan, and Alfred.

I think that we should change Part 2 to disallow MCE processing in Digital Signature XML Signature parts.  In theory, this change might have impacts on some implementations.  But I doubt it.

**Comment by murata2makoto** [comment]
Here are my proposed changes.

12.5.1 (General)

Remove the phrase "(including MCE processing before validation and subsequent processing)" in the first paragraph.

Remove the phrase "After the removal of any extensions by an MCE processor as specified in ISO/IEC 29500-3, " in the second paragraph.

Add "A Digital Signature XML Signature part shall not contain elements or attributes of the Markup Compatibility namespace as defined in Annex E. " between the second and third paragraph.

12.5.10.2

Drop the last paragraph (The Markup ...).

12.5.10.3 

Drop the last paragraph (The Markup ...).
