### ISSUE TITLE
7.5.1 Duplicate definition of “Relationships   part”

### ISSUE THREAD

**Issue by RexJaeschke** [sc34wg4/opcRevision#33]
**GB-035** |   | 7.5.1 | Para 6 | ed | The text defines “Relationships   part”, but this is already defined in clause 3.2.9.

Delete the third   sentence. Alternatively, remove the definition in clause 3.2.9. |

**Comment by murata2makoto** [comment]
I do not understand.  The  third sentence of the 6th para is  "This part holds the list of relationships for the source part. " Is this a definition?

**Comment by murata2makoto** [comment]
The definition in Clause 3 is "part containing an XML representation of relationships".

**Comment by franciscave** [comment]
As Murata-san suggests, I think I was interpreting the third sentence of the sixth paragraph of 7.5.1 as a definition. 

Actually, on re-reading it, I believe that this sentence is incorrect. It should say "This part holds the list of relationships for the source part _or package_." 

Even with this change, I am still not entirely happy, because the definition in 3.2.9 could easily have been "part containing an XML representation of relationships _for a source part or package_", in which case the sentence in the sixth para of 7.5.1 would clearly be redundant.

**Comment by franciscave** [comment]
My point is that currently the definition of "Relationships part" is partly in 3.2.9 and partly in 7.5.1. I think it would be best if it was all in 3.2.9, but let's see what folks feel after further reflection.

**Comment by murata2makoto** [comment]
How about "This part holds the list of relationships for the source"?

Unlike the definition in Clause 3, I tried here to state that all relationships for the source (and nothing else) are represented in this Relationships part associated with the source.

**Comment by franciscave** [comment]
On reflection, I am happy with 'This part holds the list of relationships for the source' in 7.5.1 and to leave 3.2.9 as it is.

**Comment by RexJaeschke** [comment]
WG4 approved on 2020-08-26, as summarized by Francis above.
