### ISSUE TITLE
Use of "might" vs. "can"

### ISSUE THREAD

**Issue by RexJaeschke** [sc34wg4/opcRevision#46]
**ISO-068** |   | General |   | ed | The document uses the verbal form   "might" in many places.   Per ISO/IEC Directives, Part 2, 2018, 7.4 and   7.5, in ISO documents,   - "may" is used to express a   permission;   - "can" is used to express a   possibility or capability.

Please replace "might"   with "can" or "may" throughout the document to avoid   ambiguity.

**Comment by murata2makoto** [comment]
Here is my [proposed rewrite](http://www.asahi-net.or.jp/~eb2m-mrt/ooxml/mightReport.htm).  It is a report created by WinMerge.  I modified the STS source but do not intend to use the modified source for further processing.

**Comment by RexJaeschke** [comment]
Although the proposal is not complicated, there are many occurrences of "might", and I think it would be best if members reviewed this off-line rather than in full committee.

**Comment by Q-Swan** [comment]
I'm prepared to go through Murata-san's proposed changes offline over the next day or two, but accessing Github again may be a challenge.

**Comment by RexJaeschke** [comment]
## 2020-07-08 Teleconference

We discussed this, but made no decisions. We really need someone to take ownership of this.

**Comment by Q-Swan** [comment]
It’s not really a good moment for thinking about this.  We are sitting on our boat at a marina in the northern Chesapeake wondering if Tropical Storm Isaias is past yet.

But, since I have already made my suggestions, I would really need (a) more information about details of the discussion, (b) to know what form decisions on individual instances need to be in, and (c) in what timeframe stuff is needed.  I’m assuming that what I provided is not usable as is.

My schedule:  I hope to back home by Monday 8/10, but will be very busy for the next two weeks.  Then I will be back in Maine with no Internet access for another week.  September will busy, but I might possibly find some time, assuming I start with good information about what is actually needed for each instance.  At the moment, that’s my major concern.

All the best,

Caroline

**Comment by Q-Swan** [comment]
I sent Rex and Murata-san a version of the ISO .docx file, with my suggested changes to Murata-san's suggestions as more tracked changes and/or comments, by email on July 15.  I was not in a position to add it to the github thread. Rex indicated on July 16 that he had got the file.  

I had assumed that you looked at those on the July call.  It seems as though that is not the case. If having my suggestions in another format is going to be substantially more convenient, I can extract my changes and provide something different.  Just let me know how you want it.  For example, would a single simple email of the sort I usually provide, be OK?  Note: I cannot conveniently submit things in perfect shape for the DR system because of having different versions of Word.

      Thanks.    Caroline
[ISO_IEC_DIS_29500-2-Word_with_trackchanges_(DIS_edit)(en)_cra.docx](https://github.com/sc34wg4/opcRevision/files/5091150/ISO_IEC_DIS_29500-2-Word_with_trackchanges_.DIS_edit.en._cra.docx)

**Comment by murata2makoto** [comment]
@Q-Swan I am afraid that I overlooked your original mail.  I checked GitHub issues and mails to the WG4 ML, but overlooked some private emails.  Since you sent your mail to the GitHub email address for this GitHub issue, your Word document is now accessible from Github.  I will read your rewrite and comments carefully.

**Comment by murata2makoto** [comment]
@Q-Swan Thank you very much for incorporating my changes to a word document and improving them.  I only slightly modified your version.  I think that we are ready to close this issue in our next teleconf.

[ISO_IEC_DIS_29500-2-Word_with_trackchanges_(DIS_edit)(en)_mu.docx](https://github.com/sc34wg4/opcRevision/files/5099744/ISO_IEC_DIS_29500-2-Word_with_trackchanges_.DIS_edit.en._mu.docx)

**Comment by franciscave** [comment]
I agree with almost all the changes proposed by Caroline and Murata-san. 

I'm uncertain about just two of Caroline's suggested uses of "may", meaning "is permissible". Specifically, I'm uncertain about its use in 9.3.3.4.1 and 9.3.3.4.2. The phrase "This element may have values such as ...." could be read as "It is permissible for this element to have values such as ...", which to me suggests some kind of enumerated constraint on the xsd:string simple type. I think that "can" is probably more appropriate in this case: "This element can contain values such as ...". I would also move these examples to follow the normative text rather than precede it, i.e. immediately before or after the coded example in each case.

**Comment by franciscave** [comment]
Unrelated point: why is the text listing possible values in 9.3.3.4.1 an Example, but in 9.3.3.4.2 it is a Note? This will presumably be resolved when we work out what we're doing with Notes and Examples more generally.

**Comment by murata2makoto** [comment]
@franciscave 

Good point.  I agree to change the two occurrences of "may".  Use "can" instead.

**Comment by RexJaeschke** [comment]
We agreed to adopt Caroline's proposed changes with Murata-san's tweaks and Francis' two edits on top of that.

**Comment by RexJaeschke** [comment]
Applied all CAR/MM edits and then applied FC edits.
