### ISSUE TITLE
12.5.9 - Unclear wording wrt RSA-SHA1 and Office's implementation

### ISSUE THREAD

**Issue by lawrenl** [sc34wg4/opcRevision#9]
Is RSA-SHA1 an example or is it the only supported algorithm for OPC? Unclear from the wording...

**Comment by murata2makoto** [comment]
This is the only permissible algorithm.  We should be more explicit about this.

This restriction is indeed a serious problem.  It implies that OPC digital signatures are unreliable.  But this is what we have now.

**Comment by RexJaeschke** [comment]
2019-03-25 F2F Meeting in Milan:

The current OPC spec refers to V1.0 of XML-Signature Syntax and Processing, W3C Recommendation, 12 February 2002. http://www.w3.org/TR/2002/REC-xmldsig-core-20020212/, which supports SHA-1 only. We note that other SHA-* hash algorithms are supported in V1.1 and higher, but for this revision of OPC, we cannot update our reference to an edition later than 1.0, because doing so would be beyond the scope of this project.

**Comment by dcleblanc** [comment]
Then that's out of date. Since Office 2013, these signatures have been produced with sha256 by default, and it was actually implemented against the 1.1 specification. It's likely that the original XML signatures that shipped in Office 2007 may have used the 1.0 specification, but since 2010, Office has used the additional hashes defined by the 1.1 specification.

In fact, we consider a sha1 hash to be insecure - this should be fixed.

**Comment by murata2makoto** [comment]
We can reference DSig 1.1 instead of 1.0.  But DSig 1.1 allows elements of the 1.1 namespace ("http://www.w3.org/2009/xmldsig11#").  They are ECKeyValue (and its children), DEREncodedKeyValue, KeyInfoReference, and X509Digest.  They will be allowed by default.

**Comment by murata2makoto** [comment]
We have to modify schemas if we use DSig 1.1.

**Comment by dcleblanc** [comment]
I apologize – I was mistaken. The additional identifiers are here:

https://www.ietf.org/rfc/rfc4051.txt, but this has since been updated with https://www.rfc-editor.org/rfc/rfc6931.txt

Also, I do not understand why we must modify schemas. I have not looked closely at the 1.1 standard as it exists today, but from a quick look, I do not see any breaking changes – though I do recall breaking changes in earlier versions of 1.1. The elements that I have seen which are deprecated are not elements which are used in document signatures. What I see are mostly ways to describe elliptic curves, and some additional elements available in the X509Data element. So it seems possible to have a Signature XML which is proper for both 1.0 and 1.1, though I have not read closely enough to be positive about that.

Further, while some algorithm URIs are defined in the 1.0 specification, the type is uri, which can be many things, and there is not a declaration that an implementation may only use those which are defined within the specification.

**Comment by murata2makoto** [comment]
@dcleblanc 

> Also, I do not understand why we must modify schemas.

I was not clear.  I meant RELAX NG schemas rather than XSD schemas.

**Comment by murata2makoto** [comment]
Here are some (but not all) of the required changes for the introduction of DSig 1.1.  We need more changes for 12.5, 12.8, 12.9, and C.4.

Changes to Clause 2(Normative References)

Add:

>   XML Signature Syntax and Processing Version 1.1, W3C Recommendation, 11 April 2013.
>   https://www.w3.org/TR/xmldsig-core1/

and remove the reference to "XML Signature Syntax and Processing".

Changes to 12.1 (General)

Replace  "XML Signature Syntax and Processing" by  "XML Signature Syntax and Processing Version 1.1".


Changes to 12.2

Replace "XML Signature Syntax and Processing" in the title by
"XML Signature Syntax and Processing Version 1.1".


Changes to 12.5.1

In the second paragraph, replace

>   "schema-valid XML document against xmldsig-core-schema.xsd, as
>   specified in the W3C Recommendation “XML-Signature Syntax and
>   Processing”, and opc-digSig.xsd (see §C.4)."

by 

>   "schema-valid XML document against xmldsig-core-schema.xsd and
>   xmldsig11-schema.xsd, as specified in the W3C Recommendation
>   “XML-Signature Syntax and Processing Version 1.1”, as well as
>   opc-digSig.xsd (see §C.4).


In the third paragraph, replace both occurrences of “XML-Signature
Syntax and Processing” by “XML-Signature Syntax and Processing
Version 1.1”.

**Comment by dcleblanc** [comment]
I apologize for being unclear in my previous response, and on reflection, I think we can clarify this topic. We have two problems which we have co-mingled.

1) We use algorithms which are not defined in XMLDsig 1.0. This is covered in  https://www.rfc-editor.org/rfc/rfc6931.txt, and the standard document should also reference RFC 6931 to resolve that issue. Also, I believe not all the algorithms we currently support are in XMLDSig 1.1, so referencing that will not solve the algorithm problem, but RFC 6931 will.

2) Support for XMLDSig 1.1 - I do not believe that we actually need any XMLDSig 1.1 elements to create signatures. If they did occur in the Signature XML, there would be a very good chance that parsers would break. Before allowing XMLDSig 1.1 elements to be present, testing should occur to ensure that existing parsers correctly ignore them, and can still correctly evaluate the signature. In any case, there are no existing implementations that can emit XMLDSig 1.1 signatures, and I would be reluctant to put anything into the standard which hasn't been tested. 

Now let's look at what 1.1 adds, and see if any of it would help:
1) There are new possible child elements under KeyInfo, but we currently can only use an X509Data element. If it does not currently, this should be reflected in the standard as being a MUST.
2) The KeyValue element can contain a new element, but we do not use a KeyValue element
3) There are several new elements used to describe elliptic curve keys, but because we use an X509Data, we don't need them, and elliptic curve signatures work now.
4) The dsig11:X509Digest element is of interest - it provides the same assurance as the xades:SigningCertificate element. However, since we always produce signatures with the xades:SigningCertificate element starting with Office 2010, there would be no additional advantage to add XMLDSig 1.1 just to get this capability.

**Comment by murata2makoto** [comment]
@dcleblanc 
Thank you for your very clear message.   A below paragraph in XML Dsig 1.0 allows algorithms not listed in DSig 1.0.  We did not understand.
> This specification defines a set of algorithms, their URIs, and requirements for implementation. Requirements are specified over implementation, not over requirements for signature use. Furthermore, the mechanism is extensible; alternative algorithms may be used by signature applications.

I understand your concern about DSig 1.1.  I agree not to reference DSig 1.1 in this revision. 

> We use algorithms which are not defined in XMLDsig 1.0. This is covered in https://www.rfc-editor.org/rfc/rfc6931.txt, and the standard document should also reference RFC 6931 to resolve that issue. Also, I believe not all the algorithms we currently support are in XMLDSig 1.1, so referencing that will not solve the algorithm problem, but RFC 6931 will.

Should we allow *all* algorithms in this RFC?  Which algorithm should be made mandatory (i.e., validators are required to support it)?   I would appreciate your input.

**Comment by murata2makoto** [comment]
If I am not mistaken, the latest version of MS-OFFCRYPTO does not provide any information about the use of SHA256 in OPC.

**Comment by murata2makoto** [comment]
I find that the currently published OPC (2012 edition) has two seemingly-conflicting requirements.

>Package producers and consumers shall support RSA-SHA1 algorithms to produce or
validate signatures. 

>Producers shall support DSA and RSA algorithms to
produce signatures. Consumers shall support DSA and RSA algorithms to validate signatures.

The current draft is based on the first requirement.

**Comment by dcleblanc** [comment]
I am unsure what's currently in MS-OFFCRYPTO - haven't looked at it recently. The following signature algorithms are recognized (based on a search of Office 15 source, I doubt that has changed, but Lawrence can check):

http://www.w3.org/2000/09/xmldsig#dsa-sha1
http://www.w3.org/2000/09/xmldsig#rsa-sha1
http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
http://www.w3.org/2001/04/xmldsig-more#rsa-sha384
http://www.w3.org/2001/04/xmldsig-more#rsa-sha512

http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha1
http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256
http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384
ttp://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512

The following hashing algorithms may be used:
http://www.w3.org/2000/09/xmldsig#sha1
http://www.w3.org/2001/04/xmlenc#sha256
http://www.w3.org/2001/04/xmldsig-more#sha384
http://www.w3.org/2001/04/xmlenc#sha512

This won't break, but it will cause the signature to evaluate as weak or invalid, depending on settings:
http://www.w3.org/2001/04/xmldsig-more#md5

The standard itself presents considerable difficulty in dealing with algorithms which are not already known in the code. There are internal tables that tell us that a given URL corresponds to which hashing algorithm - the signing algorithm is abstracted by the certificate. The result of this is that if some other algorithm URL were to show up, there would need to be a code update to support it, and/or considerable work needed to allow this to be configurable.

As to which algorithms we did use by default, we have the following:
Office 2007 - sha1 only, though some work was done later to allow certificates which were themselves signed by sha2 hashes.
Office 2010 - sha1 was default to be compatible with Office 2007, but it was capable of using all of the above.
Office 2013 and later - sha2 is default, and will flag sha1 signatures as weak, which is configurable.

Based on our current understanding of the state of these algorithms, it is my opinion that we should amend the above as follows:

Producers SHOULD support DSA algorithms for backward compatibility
Producers MUST support RSA algorithms and key lengths < 2048 bit MAY NOT be accepted
Producers MUST support ECDSA algorithms - none of the currently allowed algorithms are considered weak, and the exact curves aren't part of the signature, so support varies by the operating system.

For hashing algorithms:
MD5 MUST NOT be accepted as a valid signature
Sha1 MAY be accepted for backward compatibility and MAY be considered weak
Sha256, Sha384, and Sha512 MUST be supported

I thank you for your efforts to bring the standard in line with actual practice. It is something I was planning on doing, but then took another position. There are a number of places where the standard has options, but this signature implementation demands that some option be chosen, for example, the KeyInfo MUST contain only one X509Data/X509Certificate element. Any place where the XMLDSig standard provides options, but this implementation would not function correctly unless some specific choice were made, that should be documented.

**Comment by murata2makoto** [comment]
@dcleblanc 

Thanks.  WG4 has basically agreed to use your proposal as a basis.  Let me ask some questions for details.

First, when you write "DSA algorithms", do you mean http://www.w3.org/2000/09/xmldsig#dsa-sha1?
Likewise, when  you write "RSA algorithms", do you mean http://www.w3.org/2000/09/xmldsig#rsa-sha1, 
http://www.w3.org/2001/04/xmldsig-more#rsa-sha256, http://www.w3.org/2001/04/xmldsig-more#rsa-sha384, and http://www.w3.org/2001/04/xmldsig-more#rsa-sha512?

Second, your proposal is about producers (i.e., "Producers SHOULD" or "Producers MUST")  What are consumers recommended or required to do?

**Comment by dcleblanc** [comment]
Yes, that does need to be clarified, let me take another pass. 

For all of the following DSA and RSA signature algorithms, we also have to take into account key length.
Key length < 1024 bits, MUST NOT (both producer and consumer)
Key length >= 1024 AND < 2048 - producer SHOULD NOT, consumer MAY
Key length >= 2048 MUST

http://www.w3.org/2000/09/xmldsig#dsa-sha1
Producer - SHOULD NOT, Consumer MAY

http://www.w3.org/2000/09/xmldsig#rsa-sha1
Producer - SHOULD NOT, Consumer MAY

http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
http://www.w3.org/2001/04/xmldsig-more#rsa-sha384
http://www.w3.org/2001/04/xmldsig-more#rsa-sha512
Producer, Consumer MUST

http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha1
Producer - SHOULD NOT, Consumer MAY

http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256
http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384
http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512
Producer, Consumer MUST

The following hashing algorithms may be used:
http://www.w3.org/2000/09/xmldsig#sha1
Producer - SHOULD NOT, Consumer MAY

http://www.w3.org/2001/04/xmlenc#sha256
http://www.w3.org/2001/04/xmldsig-more#sha384
http://www.w3.org/2001/04/xmlenc#sha512
Producer, Consumer MUST

This won't break, but it will cause the signature to evaluate as weak or invalid, depending on settings:
http://www.w3.org/2001/04/xmldsig-more#md5
Producer, Consumer MUST NOT

This is just my opinion, but does reflect current Microsoft SDL standards with respect to algorithms. I would also note that new algorithms MAY be used when available, but obviously with no guarantee of interoperability. For example, we do not have a sha3 implementation, but if someone wanted to write their own producer and consumer that used it, they could do so.

Something which is not specified, but I think should be, is the allowed curves and key lengths for elliptic curve. I would need to do a bit of digging to get the current recommendation for this. I will check on that, and comment back here when I find out.

**Comment by RexJaeschke** [comment]
Discussion from the 2019-04-24 WG4 Teleconference:

After a lengthy discussion, we agreed to defer the CD ballot. 

Action Item: Murata-san will propose normative text to accommodate David’s recommendations, and will circulate that to members and implementers. 

The next teleconference will be 2019-06-19. If we have resolved this issue via email before then (Francis can’t attend that call), we can push out the CD ballot; otherwise, not.

**Comment by murata2makoto** [comment]
@dcleblanc 

Thank you.  We are almost done.

Here is another question.  Which of the algorithms you enumerated is usable for a SignatureMethod element and which is usable for a DigestMethod element?

**Comment by dcleblanc** [comment]
Everything which contains 'dsa-', 'rsa-' or 'ecdsa-' are signing algorithms, and the URLs ending in #md5, #sha1, #sha256, #sha384, and #sha512 are digest methods.

**Comment by murata2makoto** [comment]
@dcleblanc 

Thank you so much.  Here is yet another question.  Should we allow ANY algorithm for SignatureMethod and DigestMethod elements? Or, should we allow what is listed here and nothing else?

Note that currently-published OPC imposes a tight restriction on permissible algorithms of CanonicalizationMethod elements and Transforms elements, since "Consumers validating signed packages shall fail the validation if other canonicalization methods are encountered." (13.2.4.4) and "Consumers validating signed packages shall fail the validation if other transforms are encountered." (13.2.4.7).

**Comment by dcleblanc** [comment]
Only the algorithms which are enumerated above can interoperate. Because of the choice to express algorithms as URLs, as opposed to OIDs, it is very hard to be agile.

But there are also other algorithms which are defined in the RFCs, and if we put interoperability aside, then some of them are old and should not be used, but others would be fine from a security standpoint. In order to allow for growth going forward, we should not prohibit new algorithms.

To give an example, URLs are defined for the sha3 family of digest algorithms. We do not currently have a sha3 implementation in Windows, but say that there was a customer demand for this, Windows implemented the algorithm, and Office then decided to add these hashes to the list of what can possibly be configured. We shouldn't prohibit implementations from adopting additional algorithms. In a later update to this standard, we would then perhaps add these algorithms as a MAY.

Or another example is that some jurisdictions have legal requirements to use certain algorithms. If they can create producers and consumers who understand how to access those algorithms, this must be allowed.

Transforms, of which canonicalization methods are just one example, can be abused to allow attacks on the signature. We must strictly control transforms and canonicalization methods, and only adopt new ones after careful examination of the security implications. See section 2.1 of https://www.w3.org/TR/2013/NOTE-xmldsig-bestpractices-20130124/

**Comment by murata2makoto** [comment]
Here is my proposal.

First, revive the subclause for SignatureMethod elements, since we have to introduce additional requirements.

> 
> 12.5.5 SignatureMethod element
> 
> This document introduces further requirements to those defined in §4.3.2 of “XML-Signature Syntax and Processing”.
> 
> A SignatureMethod element should specify one of the following algorithms:
> 
> http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
> http://www.w3.org/2001/04/xmldsig-more#rsa-sha384
> http://www.w3.org/2001/04/xmldsig-more#rsa-sha512
> http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256
> http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384
> http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512
> 
> The RSA key length shall be equal to or longer than 1024 bits, and should be
> longer than or equal to 2048 bits.
> 
> It should not specify
> 
> http://www.w3.org/2000/09/xmldsig#dsa-sha1
> http://www.w3.org/2000/09/xmldsig#rsa-sha1
> http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha1
> 
> It may specify other algorithms.

**Comment by murata2makoto** [comment]
Second, revise 12.5.9 (DigestMethod) by replacing the second paragraph by:

> A DigestMethod element should specify one of the following algorithms:
> 
> http://www.w3.org/2001/04/xmlenc#sha256,
> http://www.w3.org/2001/04/xmldsig-more#sha384, and
> http://www.w3.org/2001/04/xmlenc#sha512
> 
> It should not specify:
> http://www.w3.org/2000/09/xmldsig#sha1
> 
> It shall not specify:
> http://www.w3.org/2001/04/xmldsig-more#md5
> 
> It may specify other algorithms.
>

**Comment by murata2makoto** [comment]
Third, in 12.8 (Generating Signatures), add the following description as part 
of reference generation:

> Reference generation shall support the following digest algorithms:
> 
> http://www.w3.org/2001/04/xmlenc#sha256,
> http://www.w3.org/2001/04/xmldsig-more#sha384, and
> http://www.w3.org/2001/04/xmlenc#sha512
> 
> It should not support http://www.w3.org/2000/09/xmldsig#sha1
> 
> It shall not support
> 
> http://www.w3.org/2001/04/xmldsig-more#md5
> 
> It may support other algorithms.

And also add the following description at the end of signature generation:


> Signature generation shall support the following algorithms:
> 
> http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
> http://www.w3.org/2001/04/xmldsig-more#rsa-sha384
> http://www.w3.org/2001/04/xmldsig-more#rsa-sha512
> http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256
> http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384
> http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512
> 
> It shall support key lengths greater than or equal to 2048.  It
> should not support key lengths less than 2048 and shall not support
> key lengths less than 1024.
> 
> It should not support:
> 
> http://www.w3.org/2000/09/xmldsig#dsa-sha1
> http://www.w3.org/2000/09/xmldsig#rsa-sha1
> http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha1
> 
> It may support other algorithms.

**Comment by murata2makoto** [comment]
Fourth, in 12.9 (Validating Signatures), add the following description as part
of reference validation:

> Reference validation shall support the following digest algorithms:
> 
> http://www.w3.org/2001/04/xmlenc#sha256,
> http://www.w3.org/2001/04/xmldsig-more#sha384, and
> http://www.w3.org/2001/04/xmlenc#sha512
> 
> It shall not support
> http://www.w3.org/2001/04/xmldsig-more#md5
> 
> It may support other algorithms including
> http://www.w3.org/2000/09/xmldsig#sha1

And also add the following description at the end of signature validation:

> Signature validation shall support the following
> algorithms specified by SignatureMethod elements:
> 
> http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
> http://www.w3.org/2001/04/xmldsig-more#rsa-sha384
> http://www.w3.org/2001/04/xmldsig-more#rsa-sha512
> http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256
> http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384
> http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512
> 
> They may support other algorithms including:
> 
> http://www.w3.org/2000/09/xmldsig#dsa-sha1
> http://www.w3.org/2000/09/xmldsig#rsa-sha1
> http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha1
> 
>

**Comment by murata2makoto** [comment]
I forgot to provide text for the addition of RFC 6931.

In Clause 2, add:

>RFC 6931, Additional XML Security Uniform Resource Identifiers (URIs),
The Internet Society, XX, 2013, D. Eastlake 3rd, https://tools.ietf.org/html/rfc6931.

Where in Clause 12 should we reference this RFC?   One possibility is to add this sentence at the end of second paragraph of 12.5.1.

> Algorithms are identified by URIs shown in this W3C recommendation or RFC 6931.
